In [3]:
"""
CSEE 5590 0002 Python for Deep Learning
ICP 3
author: Dingari Vikram
student ID: 700742014
email: vxd20140@umsystem.edu

2. Numpy
Using NumPy create random vector of size 20 having only float in the range 1-20.
Then reshape the array to 4 by 5
Then replace the max in each row by 0 (axis=1)
(you can NOT implement it via for loop)
"""

import numpy as np
a = np.arange(1,21)
print(a)
b = a.reshape(4, 5)
print(b)
#c = b.replace(max(axis=1), 0)

c = b.max(axis=1)

#row_maxes = c.max(axis=1).reshape(-1, 1)
#c[:] = np.where(c == row_maxes, 0, 1)

print(c)

[ 1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20]
[[ 1  2  3  4  5]
 [ 6  7  8  9 10]
 [11 12 13 14 15]
 [16 17 18 19 20]]
[ 5 10 15 20]


In [28]:
"""
CSEE 5590 0002 Python for Deep Learning
ICP 3
author: Dingari Vikram
student ID: 700742014
email: vxd20140@umsystem.edu
1. Create a class Employee and then do the following:
Create a data member to count the number of Employees
Create a constructor to initialize name, family, salary, department
Create a function to average salary
Create a Fulltime Employeeclass and it should inherit the properties of Employee class
Create the instances of Fulltime Employee class and Employee class and call their member functions.
"""


class Employee:
    """
    Generic Employee class with name, family, salary and department
    """

    # data member to count the number of Employees
    no_of_employees = 0

    def __init__(self, name, family_name, salary, department):
        self.__name = name
        self.__family_name = family_name
        self.salary = salary
        self.__department = department
        Employee.no_of_employees += 1

    @staticmethod
    def average_salary(employees):
        """
        function to average salary
        """
        sum = 0
        for employee in employees:
            sum += employee.salary
        return sum / Employee.no_of_employees


class FulltimeEmployee(Employee):
    """
    Full Time Employee is a sub class of Employee
    """

    def __init__(self, name, family_name, salary, department):
        super().__init__(name, family_name, salary, department)

    def full_time_benefits(self):
        print("Few benefits as full time employee.")


def main():
    employees = []
    fte1 = FulltimeEmployee("Emp1", "FamilyName1", 140000, "Management")
    fte1.full_time_benefits()
    employees.append(fte1)
    fte2 = FulltimeEmployee("Emp2", "FamilyName2", 190000, "RnD")
    employees.append(fte2)
    emp1 = Employee("Emp3", "FamilyName3", 180000, "Marketing")
    employees.append(emp1)
    emp2 = Employee("Emp4", "FamilyName4", 145000, "HR")
    employees.append(emp2)
    print("Average salary:", FulltimeEmployee.average_salary(employees))


# if _name_ == "_main_":
main()

Few benefits as full time employee.
Average salary: 163750.0
